### ISSUE TITLE
Cannot import multi-enum options

### ISSUE THREAD

**Issue by gplanchat** [synolia/oroneo#11]
An `InvalidArgumentException` is thrown by the BAP when importing `manyToMany` enum is thrown with the message `$enumCode must not be empty.`.

It is sent here : https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EntityExtendBundle/Tools/ExtendHelper.php#L272

At this point https://github.com/synolia/oroneo/blob/master/ImportExport/Serializer/OptionSerializer.php#L45

Here is the config I have in `$config` variable :

```
object(Oro\Bundle\EntityConfigBundle\Config\Config) {
  'id': object(Oro\Bundle\EntityConfigBundle\Config\Id\FieldConfigId) {
    'scope': 'enum'
    'className': 'Oro\\Bundle\\ProductBundle\\Entity\\Product'
    'fieldName': 'foo_field'
    'fieldType': 'manyToMany'
  }
  'values': []
}
```

**Comment by Djamy** [comment]
We are working on this.
The fix will be released next week if everything is OK for us.

**Comment by Djamy** [comment]
This should be resolved with our last [commit](https://github.com/synolia/oroneo/commit/bb12b722589f7d82dab7cd18ed51e4a930783cfa); feel free to try and to open another one if you encounter any other issue.
