### ISSUE TITLE
[Question] Compatibility with OroCommerce 1.0.0

### ISSUE THREAD

**Issue by tom00** [synolia/oroneo#14]
Hi,

Do you have in the nearest timeline (upcoming days/weeks) plans to make Oroneo compatible with the latest stable version of OroCommerce?

Thanks,
Tomasz

**Comment by Djamy** [comment]
Hi,

Sorry for the delay.
Many features were released by Oro and we need to adjust a little and add a lot.
So, ATM we do not have a fixed plan on this bundle.
