### ISSUE TITLE
The localized configuration fails to display

### ISSUE THREAD

**Issue by gplanchat** [synolia/oroneo#2]
There have been a refactoring on the last commit, version 0.2.0, the localization configuration breaks :

```
Fatal error: Uncaught Error: Call to undefined method Oro\Bundle\LocaleBundle\Helper\LocalizationHelper::getAll() in /.../vendor/synolia/oroneo/Manager/OroFieldSelectManager.php:59 Stack trace:
#0 /.../vendor/synolia/oroneo/Form/Type/LocalizationMappingType.php(50): Synolia\Bundle\OroneoBundle\Manager\OroFieldSelectManager->getLocalizationChoices()
#1 /.../vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php(187): Synolia\Bundle\OroneoBundle\Form\Type\LocalizationMappingType->buildForm(Object(Symfony\Component\Form\FormBuilder), Array)
#2 /.../vendor/symfony/symfony/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeDataCollectorProxy.php(110): Symfony\Component\Form\ResolvedFormType->buildForm(Object(Symfony\Component\Form\FormBuilder), Array)
```

I'll look into the code

**Comment by Djamy** [comment]
Hi, and thanks for this issue.

We know about this bug and it's fixed but not yet released.

We have planned to commit a new minor version today with this fixed and some others adjustments :)

**Comment by Djamy** [comment]
You'll find the fix [here if you want to check it](https://github.com/synolia/oroneo/commit/9457f3748ac1d81d8cdff50d228d234dae65071a#diff-65f689b70f6cb80636c208e7ec4a6404R73).

That should resolve this issue but reopen it if it is not the case.

**Comment by gplanchat** [comment]
Yes, it works now

Thanks
