### ISSUE TITLE
Assets collection attribute type management (Akeneo EE)

### ISSUE THREAD

**Issue by gplanchat** [synolia/oroneo#4]
There is no management for the `pim_assets_collection` attribute type in the connector.

This attribute type is only present in the EE of Akeneo

**Comment by Rmnndr** [comment]
Thanks for your feedback.
We've also seen your PR about this issue. We now must spend a quick time to analyze the code you suggest to merge it or not.

Notice that, even if this bundlle must be extendable, we don't plan to manage Enterprise features in this public version of the conncector.

**Comment by gplanchat** [comment]
Indeed, you don't want to support the EE features, I can understand this fact

I made the pr #8 to make possible to easily extend the bundle without rewriting too much code

**Comment by Rmnndr** [comment]
We saw it, thank you.

As noticed on an other issue, we must plan time really quickly to analyze all the suggested contributions.

**Comment by Djamy** [comment]
Thanks @gplanchat for your PR #8 that would permit to handle the mapping in an easier way.
