### ISSUE TITLE
The attributes import produces errors in the Oro menu

### ISSUE THREAD

**Issue by gplanchat** [synolia/oroneo#6]
For the record, the attributes import produces errors in the Oro menu on beta 5 (reported as orocommerce/orocommerce#13)

**Comment by gplanchat** [comment]
Thanks to @sergeyz I found the issue and made PR #7

**Comment by Rmnndr** [comment]
Thanks for your contribution. 
Time must be quickly planned for an global PR/code review and a global merge of the all suggestions,
