### ISSUE TITLE
Cannot change the default locale to use with attributes and options labels

### ISSUE THREAD

**Issue by gplanchat** [synolia/oroneo#9]
There is no option to change the mapping used for the attribute and options labels.

The locale `fr_FR` is made mandatory and used as the desired locale, which may not be the desired one on all installs.

https://github.com/synolia/oroneo/blob/master/Migrations/Data/ORM/SetDefaultMappings.php#L55
https://github.com/synolia/oroneo/blob/master/Migrations/Data/ORM/SetDefaultMappings.php#L65

**Comment by Djamy** [comment]
I see what you mean here. Good point.

We'll treat this issue as soon as possible, thanks.

**Comment by Djamy** [comment]
We fixed this in our last [commit](https://github.com/synolia/oroneo/commit/bb12b722589f7d82dab7cd18ed51e4a930783cfa).

Thanks for reporting :)
